//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro
    {
        public int NCuenta { get; set; }
        public string NombreCompleto { get; set; }
        public string Profesion { get; set; }
        public string Carrera { get; set; }
        public Nullable<int> Edad { get; set; }
    }
}
